export const products = [
  {
    id: "1",
    name: "Lynette Armchair",
    description: "A comfortable and stylish armchair perfect for any living room.",
    price: 340,
    image: "https://raw.githubusercontent.com/gammarinaldi/images/main/Lynette-Armchair.webp",
    material: "Leather",
    dimensions: "31 x 29 x 28 cm",
    finish: "Oil Finish",
    weight: "6.2 Kilograms",
    colors: ["#E6B17E", "#9CA365", "#2C2C2C"],
  },
  {
    id: "2",
    name: "Monet Armchair",
    description: "An elegant armchair inspired by classic French design.",
    price: 850,
    image: "https://raw.githubusercontent.com/gammarinaldi/images/main/Monet-Armchair.webp",
    material: "Velvet",
    dimensions: "32 x 34 x 37 cm",
    finish: "Wood Dye",
    weight: "8.2 Kilograms",
    colors: ["#F6A834", "#2C2C2C", "#9A9A9A", "#7CC0D8"],
  },
  {
    id: "3",
    name: "Eclipse Rosto Armchair",
    description: "A modern armchair with a unique design that stands out in any room.",
    price: 280,
    image: "https://raw.githubusercontent.com/gammarinaldi/images/main/Eclipse-Rosto-Armchair.webp",
    material: "Cotton",
    dimensions: "29 x 21 x 34 cm",
    finish: "Wax",
    weight: "6.4 Kilograms",
    colors: ["#D4A181", "#E6B17E", "#7581CA", "#7CC0D8"],
  },
]
